# Use root/example as user/password credentials
version: "3.1"

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    env_file:
    - .env
    environment:
      CONFIG_MONGODB_HOST: mongo
      CONFIG_MONGODB_POST: 27017
      CONFIG_MONGODB_USERNAME: root
      CONFIG_MONGODB_PASSWORD: example
      CONFIG_OAUTH2_ACCESS_TOKEN_URI: https://github.com/login/oauth/access_token
      CONFIG_OAUTH2_AUTHORIZATION_URI: https://github.com/login/oauth/authorize
      CONFIG_AUTH_REDIRECT_URI: http:///localhost:3000/auth/github/user/ # test -> user
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
      args:
      - CONFIG_API_URL=http://api:3000
      - CONFIG_API_PUBLIC_URL=http://localhost:3000
    ports:
      - 8080:3000
    environment:
      CONFIG_API_URL: http://api:3000
      CONFIG_API_PUBLIC_URL: http://localhost:3000
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example