# Use root/example as user/password credentials
version: "3.1"

services:
  code:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
    - .env
    environment:
      CONFIG_MONGODB_HOST: mongo
      CONFIG_MONGODB_POST: 27017
      CONFIG_MONGODB_USERNAME: root
      CONFIG_MONGODB_PASSWORD: example
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
