# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI API

on:
  push:
    paths:
    - 'api/**'
  pull_request:

jobs:
  test-api:
    defaults:
      run:
        working-directory: api
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Cache
      uses: actions/cache@v2.1.3
      with:
        path: api/node_modules 
        key: test-api-${BRANCH_NAME}

    - name: npm install
      run: npm ci
    - name: build
      run: npm run build --if-present
    - name: test
      run: npm test
    - name: articaft
      uses: actions/upload-artifact@v2
      with:
        name: coverage-api
        path: api/coverage